apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-app-deployment
  labels:
    app: liatrio-app
specs:
  replicas: 1
  selector:
    matchLabels:
      app: liatrio-app
  template:
    metadata:
      labels:
        app: liatrio-app
    spec:
      containers:
      - name: liatrio-app
        image: kelbycodes/liatrio-app:1.0
        ports:
          - containerPort: 8080
      environment:
          PORT: 8080