apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-app-deployment
  namespace: default
  labels:
    app: liatrio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liatrio-app
  template:
    metadata:
      labels:
        app: liatrio-app
    spec:
      containers:
      - name: liatrio-app
        image: us-south1-docker.pkg.dev/GOOGLE_PROJECT/liatrio-app/node:latest
        ports:
        - containerPort: 8080
          protocol: TCP