apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liatrio-app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: liatrio-static-ip
  namespace: default
spec:
  defaultBackend:
    service:
      name: liatrio-app-web-service
      port:
        number: 8080