# test

name: cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:

    - name: test
      run: echo test

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true
    - name: Confirm gcloud cli installed properly
      run: echo gcloud cli installed properly!


    - name: get service & ingress lists
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-south1
        kubectl get service -o wide
        kubectl get ingress -A -o wide

    - name: test2
      run: echo test2

    - name: test install w3m
      run: sudo apt-get install w3m

    - name: test3
      run: echo test3

    - name: open web browser
      run: open "https://stackoverflow.com" 
  
    - name: test4
      run: echo test4
  