name: cleanup-workflow

on:
  workflow_dispatch:

jobs:
  cleanup-workflow:
    runs-on: ubuntu-latest
    steps:

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true
      
    # - name: get service & ingress lists
    #   run: |
    #     gcloud container clusters get-credentials autopilot-cluster-1 --region us-south1
    #     kubectl get service -o wide
    #     kubectl get ingress -A -o wide
    #   # echo ******************
    #   # kubectl get liatrio-app-ingress -o jsonpath='{.spec.clusterIP}'        

    - name: get service & ingress lists
      run: |
        gcloud container clusters get-credentials liatrio-app-cluster-1 --region us-central1-a
        kubectl get service -o wide
        kubectl get ingress -A -o wide
      # echo ******************
      # kubectl get liatrio-app-ingress -o jsonpath='{.spec.clusterIP}'        
  
    - name: Delete web service
      run: kubectl delete service liatrio-app-web-service
      
    - name: Delete ingress
      run: kubectl delete ingress liatrio-app-ingress

    - name: Delete liatrio-app-cluster-1
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: gcloud container clusters delete liatrio-app-cluster-1 --project=$GOOGLE_PROJECT --location=us-central1-a
