name: Build and Deploy

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v3

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true
    - name: Confirm gcloud cli installed properly
      run: echo gcloud cli installed properly!

    - name: build and push the docker image to artifact registry
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-south1-docker.pkg.dev
        docker build -t us-south1-docker.pkg.dev/$GOOGLE_PROJECT/liatrio-app/node:12 .
        docker push us-south1-docker.pkg.dev/$GOOGLE_PROJECT/liatrio-app/node:12
    - name: Confirm docker image pushed to artifact registry properly
      run: echo Docker image pushed to artifact registry properly!

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-south1
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources/deployment.yaml
        kubectl apply -f resources/deployment.yaml
    - name: Confirm Docker image deployed to gke kluster properly
      run: echo Docker image deployed to gke kluster properly!

    - name: Apply web-service to cluster
      run: kubectl apply -f resources/web-service.yaml
    - name: Confirm web-service applied properly
      run: echo web-service applied properly!
      
    - name: Apply ingress to gke
      run: kubectl apply -f resources/ingress.yaml
    - name: Confirm ingress applied properly
      run: echo Ingress applied properly!
      
    - name: get service list
      run: kubectl get service -o wide

    - name: get ingress list
      run: kubectl get ingress -A -o json