name: Docker Image CI

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
  workflow_dispatch:

# working block
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build -t kelbycodes/liatrio-app:1.0 .
    
#     - name: Confirm container build
#       run: echo Docker Container Built!

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v3

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push the docker image to artifact registry
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-south1-docker.pkg.dev
        docker build -t us-south1-docker.pkg.dev/$GOOGLE_PROJECT/liatrio-app .
        docker push us-south1-docker.pkg.dev/$GOOGLE_PROJECT/liatrio-app

