name: get-ingress-url-workflow

on:
  workflow_dispatch:

jobs:
  get-ingress-url-workflow:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v3

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: get service & ingress lists
      run: |
        gcloud container clusters get-credentials liatrio-app-cluster-1 --location=us-central1-a
        kubectl get service -o wide
        kubectl get ingress -A -o wide

    - name: test overwrite file
      run: echo "foo-bar" > 'latest-url-link.txt'